// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/icalder/enttest/ent/predicate"
	"github.com/icalder/enttest/ent/registry"
	"github.com/icalder/enttest/ent/repository"
)

// RegistryUpdate is the builder for updating Registry entities.
type RegistryUpdate struct {
	config
	hooks    []Hook
	mutation *RegistryMutation
}

// Where appends a list predicates to the RegistryUpdate builder.
func (ru *RegistryUpdate) Where(ps ...predicate.Registry) *RegistryUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetName sets the "name" field.
func (ru *RegistryUpdate) SetName(s string) *RegistryUpdate {
	ru.mutation.SetName(s)
	return ru
}

// AddRepositoryIDs adds the "repositories" edge to the Repository entity by IDs.
func (ru *RegistryUpdate) AddRepositoryIDs(ids ...int) *RegistryUpdate {
	ru.mutation.AddRepositoryIDs(ids...)
	return ru
}

// AddRepositories adds the "repositories" edges to the Repository entity.
func (ru *RegistryUpdate) AddRepositories(r ...*Repository) *RegistryUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.AddRepositoryIDs(ids...)
}

// Mutation returns the RegistryMutation object of the builder.
func (ru *RegistryUpdate) Mutation() *RegistryMutation {
	return ru.mutation
}

// ClearRepositories clears all "repositories" edges to the Repository entity.
func (ru *RegistryUpdate) ClearRepositories() *RegistryUpdate {
	ru.mutation.ClearRepositories()
	return ru
}

// RemoveRepositoryIDs removes the "repositories" edge to Repository entities by IDs.
func (ru *RegistryUpdate) RemoveRepositoryIDs(ids ...int) *RegistryUpdate {
	ru.mutation.RemoveRepositoryIDs(ids...)
	return ru
}

// RemoveRepositories removes "repositories" edges to Repository entities.
func (ru *RegistryUpdate) RemoveRepositories(r ...*Repository) *RegistryUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.RemoveRepositoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RegistryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RegistryUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RegistryUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RegistryUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RegistryUpdate) check() error {
	if v, ok := ru.mutation.Name(); ok {
		if err := registry.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Registry.name": %w`, err)}
		}
	}
	return nil
}

func (ru *RegistryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(registry.Table, registry.Columns, sqlgraph.NewFieldSpec(registry.FieldID, field.TypeUUID))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Name(); ok {
		_spec.SetField(registry.FieldName, field.TypeString, value)
	}
	if ru.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   registry.RepositoriesTable,
			Columns: []string{registry.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedRepositoriesIDs(); len(nodes) > 0 && !ru.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   registry.RepositoriesTable,
			Columns: []string{registry.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RepositoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   registry.RepositoriesTable,
			Columns: []string{registry.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{registry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RegistryUpdateOne is the builder for updating a single Registry entity.
type RegistryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RegistryMutation
}

// SetName sets the "name" field.
func (ruo *RegistryUpdateOne) SetName(s string) *RegistryUpdateOne {
	ruo.mutation.SetName(s)
	return ruo
}

// AddRepositoryIDs adds the "repositories" edge to the Repository entity by IDs.
func (ruo *RegistryUpdateOne) AddRepositoryIDs(ids ...int) *RegistryUpdateOne {
	ruo.mutation.AddRepositoryIDs(ids...)
	return ruo
}

// AddRepositories adds the "repositories" edges to the Repository entity.
func (ruo *RegistryUpdateOne) AddRepositories(r ...*Repository) *RegistryUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.AddRepositoryIDs(ids...)
}

// Mutation returns the RegistryMutation object of the builder.
func (ruo *RegistryUpdateOne) Mutation() *RegistryMutation {
	return ruo.mutation
}

// ClearRepositories clears all "repositories" edges to the Repository entity.
func (ruo *RegistryUpdateOne) ClearRepositories() *RegistryUpdateOne {
	ruo.mutation.ClearRepositories()
	return ruo
}

// RemoveRepositoryIDs removes the "repositories" edge to Repository entities by IDs.
func (ruo *RegistryUpdateOne) RemoveRepositoryIDs(ids ...int) *RegistryUpdateOne {
	ruo.mutation.RemoveRepositoryIDs(ids...)
	return ruo
}

// RemoveRepositories removes "repositories" edges to Repository entities.
func (ruo *RegistryUpdateOne) RemoveRepositories(r ...*Repository) *RegistryUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.RemoveRepositoryIDs(ids...)
}

// Where appends a list predicates to the RegistryUpdate builder.
func (ruo *RegistryUpdateOne) Where(ps ...predicate.Registry) *RegistryUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RegistryUpdateOne) Select(field string, fields ...string) *RegistryUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Registry entity.
func (ruo *RegistryUpdateOne) Save(ctx context.Context) (*Registry, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RegistryUpdateOne) SaveX(ctx context.Context) *Registry {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RegistryUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RegistryUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RegistryUpdateOne) check() error {
	if v, ok := ruo.mutation.Name(); ok {
		if err := registry.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Registry.name": %w`, err)}
		}
	}
	return nil
}

func (ruo *RegistryUpdateOne) sqlSave(ctx context.Context) (_node *Registry, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(registry.Table, registry.Columns, sqlgraph.NewFieldSpec(registry.FieldID, field.TypeUUID))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Registry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, registry.FieldID)
		for _, f := range fields {
			if !registry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != registry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Name(); ok {
		_spec.SetField(registry.FieldName, field.TypeString, value)
	}
	if ruo.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   registry.RepositoriesTable,
			Columns: []string{registry.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedRepositoriesIDs(); len(nodes) > 0 && !ruo.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   registry.RepositoriesTable,
			Columns: []string{registry.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RepositoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   registry.RepositoriesTable,
			Columns: []string{registry.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Registry{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{registry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
