// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/icalder/entproj/ent/artifact"
	"github.com/icalder/entproj/ent/registry"
	"github.com/icalder/entproj/ent/repository"
	"github.com/icalder/entproj/ent/schema"
	"github.com/rs/xid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	artifactMixin := schema.Artifact{}.Mixin()
	artifactMixinFields0 := artifactMixin[0].Fields()
	_ = artifactMixinFields0
	artifactFields := schema.Artifact{}.Fields()
	_ = artifactFields
	// artifactDescDigest is the schema descriptor for digest field.
	artifactDescDigest := artifactFields[0].Descriptor()
	// artifact.DigestValidator is a validator for the "digest" field. It is called by the builders before save.
	artifact.DigestValidator = artifactDescDigest.Validators[0].(func(string) error)
	// artifactDescMediaType is the schema descriptor for mediaType field.
	artifactDescMediaType := artifactFields[1].Descriptor()
	// artifact.MediaTypeValidator is a validator for the "mediaType" field. It is called by the builders before save.
	artifact.MediaTypeValidator = artifactDescMediaType.Validators[0].(func(string) error)
	// artifactDescID is the schema descriptor for id field.
	artifactDescID := artifactMixinFields0[0].Descriptor()
	// artifact.DefaultID holds the default value on creation for the id field.
	artifact.DefaultID = artifactDescID.Default.(func() xid.ID)
	registryFields := schema.Registry{}.Fields()
	_ = registryFields
	// registryDescName is the schema descriptor for name field.
	registryDescName := registryFields[1].Descriptor()
	// registry.NameValidator is a validator for the "name" field. It is called by the builders before save.
	registry.NameValidator = registryDescName.Validators[0].(func(string) error)
	repositoryMixin := schema.Repository{}.Mixin()
	repositoryMixinFields0 := repositoryMixin[0].Fields()
	_ = repositoryMixinFields0
	repositoryFields := schema.Repository{}.Fields()
	_ = repositoryFields
	// repositoryDescName is the schema descriptor for name field.
	repositoryDescName := repositoryFields[0].Descriptor()
	// repository.NameValidator is a validator for the "name" field. It is called by the builders before save.
	repository.NameValidator = repositoryDescName.Validators[0].(func(string) error)
	// repositoryDescID is the schema descriptor for id field.
	repositoryDescID := repositoryMixinFields0[0].Descriptor()
	// repository.DefaultID holds the default value on creation for the id field.
	repository.DefaultID = repositoryDescID.Default.(func() xid.ID)
}
