// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/icalder/enttest/ent/registry"
	"github.com/icalder/enttest/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	registryFields := schema.Registry{}.Fields()
	_ = registryFields
	// registryDescName is the schema descriptor for name field.
	registryDescName := registryFields[1].Descriptor()
	// registry.NameValidator is a validator for the "name" field. It is called by the builders before save.
	registry.NameValidator = registryDescName.Validators[0].(func(string) error)
}
