// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Artifact is the predicate function for artifact builders.
type Artifact func(*sql.Selector)

// Registry is the predicate function for registry builders.
type Registry func(*sql.Selector)

// Repository is the predicate function for repository builders.
type Repository func(*sql.Selector)
